Repository urbit/urbit, pull requests merged in 2019-10, with the labels that each got.

#1786 Add Nix Attributes to Build Container Images
  nix/pkgs/default.nix
  nix/pkgs/urbit/image.nix
  sh/image
Labels: build

#1803 Implement chat-cli
  pkg/arvo/app/chat-cli.hoon
  pkg/arvo/app/chat-store.hoon
  pkg/arvo/lib/chat-json.hoon
  pkg/arvo/lib/chat/eval.hoon
  pkg/arvo/lib/hood/drum.hoon
Labels: userspace

#1816 Chat-cli: glyph fixes
  pkg/arvo/app/chat-cli.hoon
Labels: userspace

#1851 chat-cli: update prompt on ;join
  pkg/arvo/app/chat-cli.hoon
Labels: chat

#1889 chat-hook: use sender's timestamp
  pkg/arvo/app/chat-hook.hoon
Labels: chat
