Repository urbit/urbit, pull requests merged in 2020-12, with the labels that each got.

#4052 dojo: correct mark conversion scry path
  pkg/arvo/app/dojo.hoon
Labels: dojo

#4065 arvo: remove unused app files, libraries, and imports
  pkg/arvo/app/chat-cli.hoon
  pkg/arvo/app/chat-hook.hoon
  pkg/arvo/app/chat-view.hoon
  pkg/arvo/app/contact-hook.hoon
  pkg/arvo/app/contact-view.hoon
  pkg/arvo/app/group-hook.hoon
  pkg/arvo/app/group-pull-hook.hoon
  pkg/arvo/app/group-push-hook.hoon
  pkg/arvo/app/group-store.hoon
  pkg/arvo/app/link-listen-hook.hoon
  pkg/arvo/app/link-proxy-hook.hoon
  pkg/arvo/app/link-store.hoon
  pkg/arvo/app/link-view.hoon
  pkg/arvo/app/permission-group-hook.hoon
  pkg/arvo/app/permission-hook.hoon
  pkg/arvo/app/permission-store.hoon
  pkg/arvo/app/publish.hoon
  pkg/arvo/app/soto.hoon
  pkg/arvo/gen/group-hook/add.hoon
  pkg/arvo/gen/group-hook/remove.hoon
  pkg/arvo/gen/link-store/note.hoon
  pkg/arvo/gen/link-store/save.hoon
  pkg/arvo/lib/group.hoon
  pkg/arvo/lib/hood/drum.hoon
  pkg/arvo/lib/link-store.hoon
  pkg/arvo/lib/metadata.hoon
  pkg/arvo/lib/permission-json.hoon
  pkg/arvo/lib/soto.hoon
  pkg/arvo/mar/group/hook-action.hoon
  pkg/arvo/mar/link/action.hoon
  pkg/arvo/mar/link/initial.hoon
  pkg/arvo/mar/link/listen-action.hoon
  pkg/arvo/mar/link/listen-poke.hoon
  pkg/arvo/mar/link/listen-update.hoon
  pkg/arvo/mar/link/update.hoon
  pkg/arvo/mar/link/view-action.hoon
  pkg/arvo/mar/permission/action.hoon
  pkg/arvo/mar/permission/group-hook-action.hoon
  pkg/arvo/mar/permission/hook-action.hoon
  pkg/arvo/mar/permission/update.hoon
  pkg/arvo/mar/publish/action.hoon
  pkg/arvo/mar/publish/comment.hoon
  pkg/arvo/mar/publish/info.hoon
  pkg/arvo/mar/publish/notebook-delta.hoon
  pkg/arvo/mar/publish/primary-delta.hoon
  pkg/arvo/sur/group-hook.hoon
  pkg/arvo/sur/link-listen-hook.hoon
  pkg/arvo/sur/link-store.hoon
  pkg/arvo/sur/link-view.hoon
  pkg/arvo/sur/link.hoon
  pkg/arvo/sur/permission-group-hook.hoon
  pkg/arvo/sur/permission-hook.hoon
  pkg/arvo/sur/permission-store.hoon
  pkg/arvo/sur/publish.hoon
  pkg/arvo/ted/ph/group-rejoin.hoon
Labels: breach

#4060 hoon: updates +end, +lsh, and +rsh to use $bite
  bin/ivory.pill
  bin/solid.pill
  pkg/arvo/app/chat-cli.hoon
  pkg/arvo/app/chat-hook.hoon
  pkg/arvo/app/dbug.hoon
  pkg/arvo/app/dojo.hoon
  pkg/arvo/app/file-server.hoon
  pkg/arvo/app/glob.hoon
  pkg/arvo/app/hood.hoon
  pkg/arvo/gen/help.hoon
  pkg/arvo/gen/hood/claz-invites.hoon
  pkg/arvo/gen/hood/moon.hoon
  pkg/arvo/gen/key.hoon
  pkg/arvo/gen/reload-event.hoon
  pkg/arvo/lib/base64.hoon
  pkg/arvo/lib/bip32.hoon
  pkg/arvo/lib/bip39.hoon
  pkg/arvo/lib/der.hoon
  pkg/arvo/lib/hood/drum.hoon
  pkg/arvo/lib/hood/helm.hoon
  pkg/arvo/lib/keygen.hoon
  pkg/arvo/lib/language-server/complete.hoon
  pkg/arvo/lib/language-server/easy-print.hoon
  pkg/arvo/lib/link-store.hoon
  pkg/arvo/lib/old-phon.hoon
  pkg/arvo/lib/pkcs.hoon
  pkg/arvo/lib/primitive-rsa.hoon
  pkg/arvo/lib/ring.hoon
  pkg/arvo/lib/shoe.hoon
  pkg/arvo/lib/test/runner.hoon
  pkg/arvo/mar/eth/txs.hoon
  pkg/arvo/mar/hash.hoon
  pkg/arvo/mar/udon.hoon
  pkg/arvo/mar/umd.hoon
  pkg/arvo/sys/arvo.hoon
  pkg/arvo/sys/hoon.hoon
  pkg/arvo/sys/vane/ames.hoon
  pkg/arvo/sys/vane/clay.hoon
  pkg/arvo/sys/vane/eyre.hoon
  pkg/arvo/sys/vane/gall.hoon
  pkg/arvo/sys/vane/jael.hoon
  pkg/arvo/sys/zuse.hoon
  pkg/arvo/ted/aqua/eyre-azimuth.hoon
  pkg/arvo/ted/eth/send-txs.hoon
  pkg/arvo/ted/test.hoon
  pkg/arvo/tests/sys/zuse/crypto/ripemd.hoon
  pkg/urbit/jets/c/end.c
  pkg/urbit/jets/c/lsh.c
  pkg/urbit/jets/c/rsh.c
Labels: breach

#4051 Ames flat packet format
  bin/ivory.pill
  bin/solid.pill
  pkg/arvo/sys/vane/ames.hoon
  pkg/arvo/ted/aqua/ames.hoon
  pkg/arvo/ted/ph/hi-comet-az.hoon
  pkg/arvo/tests/sys/vane/ames.hoon
  pkg/urbit/vere/io/ames.c
Labels: breach

#3903 vere/aes_siv: check claimed length
  pkg/urbit/jets/e/aes_siv.c
Labels: breach

#4000 chat-cli: mvp graph-store migration
  pkg/arvo/app/chat-cli.hoon
Labels: chat, graph

#4072 arvo: embrace filesystem, add %lull
  bin/solid.pill
  pkg/arvo/gen/hood/reboot.hoon
  pkg/arvo/gen/hood/reload-desk.hoon
  pkg/arvo/gen/hood/reload.hoon
  pkg/arvo/gen/hood/reset.hoon
  pkg/arvo/gen/ivory.hoon
  pkg/arvo/gen/reload-event.hoon
  pkg/arvo/lib/hood/helm.hoon
  pkg/arvo/lib/pill.hoon
  pkg/arvo/sys/arvo.hoon
  pkg/arvo/sys/lull.hoon
  pkg/arvo/sys/vane/clay.hoon
  pkg/arvo/sys/vane/dill.hoon
  pkg/arvo/sys/zuse.hoon
  pkg/urbit/include/c/motes.h
  pkg/urbit/vere/pier.c
Labels: breach

#4036 various: start threads with unit of tuple args
  pkg/arvo/app/dojo.hoon
  pkg/arvo/app/glob.hoon
  pkg/arvo/app/observe-hook.hoon
  pkg/arvo/app/spider.hoon
  pkg/arvo/ted/build-cast.hoon
  pkg/arvo/ted/build-file.hoon
  pkg/arvo/ted/build-mark.hoon
  pkg/arvo/ted/diff.hoon
  pkg/arvo/ted/dns/address.hoon
  pkg/arvo/ted/glob.hoon
  pkg/arvo/ted/graph/create.hoon
  pkg/arvo/ted/graph/delete.hoon
  pkg/arvo/ted/graph/groupify.hoon
  pkg/arvo/ted/graph/join.hoon
  pkg/arvo/ted/graph/leave.hoon
  pkg/arvo/ted/graph/restore.hoon
  pkg/arvo/ted/hi.hoon
  pkg/arvo/ted/invite/accepted-graph.hoon
  pkg/arvo/ted/migrate-channels.hoon
  pkg/arvo/ted/read.hoon
  pkg/arvo/ted/test.hoon
  pkg/arvo/ted/time.hoon
  pkg/arvo/ted/tree.hoon
Labels: breach, dojo, generators

#4077 ted: update straggler threads for vase unit change
  pkg/arvo/ted/aqua/dill.hoon
  pkg/arvo/ted/group/on-leave.hoon
  pkg/arvo/ted/group/on-remove-member.hoon
Labels: breach

#4027 king: port the new lmdb event log changes.
  pkg/hs/urbit-eventlog-lmdb/lib/Urbit/EventLog/Event.hs
  pkg/hs/urbit-eventlog-lmdb/lib/Urbit/EventLog/LMDB.hs
  pkg/hs/urbit-eventlog-lmdb/package.yaml
  pkg/hs/urbit-king/lib/Urbit/King/EventBrowser.hs
  pkg/hs/urbit-king/lib/Urbit/Vere/LMDB.hs
  pkg/hs/urbit-king/lib/Urbit/Vere/Pier.hs
  pkg/hs/urbit-king/lib/Urbit/Vere/Serf.hs
Labels: breach

#4076 u3: disable +scot and +scow jets
  pkg/urbit/jets/tree.c
Labels: breach

#4087 Merge philip/testnet back into na-release/candidate
  bin/ivory.pill
  bin/solid.pill
  pkg/arvo/app/azimuth-tracker.hoon
  pkg/arvo/app/chat-hook.hoon
  pkg/arvo/app/chat-store.hoon
  pkg/arvo/app/contact-hook.hoon
  pkg/arvo/app/contact-store.hoon
  pkg/arvo/app/eth-watcher.hoon
  pkg/arvo/app/glob.hoon
  pkg/arvo/app/graph-store.hoon
  pkg/arvo/app/group-store.hoon
  pkg/arvo/app/invite-store.hoon
  pkg/arvo/app/landscape/index.html
  pkg/arvo/app/lens.hoon
  pkg/arvo/app/metadata-hook.hoon
  pkg/arvo/app/metadata-store.hoon
  pkg/arvo/gen/aqua-export.hoon
  pkg/arvo/lib/hood/kiln.hoon
  pkg/arvo/lib/migrate.hoon
  pkg/arvo/lib/ph/io.hoon
  pkg/arvo/lib/pull-hook.hoon
  pkg/arvo/lib/strandio.hoon
  pkg/arvo/mar/contact/view-action.hoon
  pkg/arvo/mar/import.hoon
  pkg/arvo/mar/metadata/hook-action.hoon
  pkg/arvo/sur/eth-watcher.hoon
  pkg/arvo/sys/vane/gall.hoon
  pkg/arvo/sys/vane/jael.hoon
  pkg/arvo/sys/zuse.hoon
  pkg/arvo/ted/eth-watcher.hoon
  pkg/arvo/ted/ph/migrate/breach.hoon
  pkg/arvo/ted/ph/migrate/commit-home.hoon
  pkg/arvo/ted/ph/migrate/import.hoon
  pkg/arvo/ted/ph/migrate/init.hoon
  pkg/arvo/ted/ph/migrate/make-chats.hoon
  pkg/arvo/ted/ph/migrate/make-graphs.hoon
  pkg/arvo/ted/ph/migrate/make-groups.hoon
  pkg/arvo/ted/ph/migrate/post-import-chat.hoon
  pkg/arvo/ted/ph/migrate/post-import-graphs.hoon
  pkg/arvo/ted/ph/migrate/post-import-groups.hoon
  pkg/arvo/ted/ph/migrate/post-import-metadata-contacts.hoon
  pkg/arvo/ted/ph/migrate/send-his.hoon
  pkg/arvo/ted/ph/migrate/start.hoon
  pkg/arvo/ted/ph/start-drivers.hoon
  pkg/urbit/vere/io/fore.c
  pkg/urbit/version
Labels: breach

#4088 ames: don't crash on forward-lane scry
  pkg/arvo/sys/vane/ames.hoon
Labels: breach

#4097 zuse: lift moves out of +able
  pkg/arvo/app/aqua.hoon
  pkg/arvo/app/azimuth-tracker.hoon
  pkg/arvo/app/eth-watcher.hoon
  pkg/arvo/app/herm.hoon
  pkg/arvo/app/language-server.hoon
  pkg/arvo/app/ping.hoon
  pkg/arvo/app/pool-group-hook.hoon
  pkg/arvo/gen/aqua/init.hoon
  pkg/arvo/gen/hood/moon-breach.hoon
  pkg/arvo/gen/hood/moon-cycle-keys.hoon
  pkg/arvo/gen/hood/moon.hoon
  pkg/arvo/gen/key.hoon
  pkg/arvo/lib/aqua-azimuth.hoon
  pkg/arvo/lib/azimuthio.hoon
  pkg/arvo/lib/ethio.hoon
  pkg/arvo/lib/hood/helm.hoon
  pkg/arvo/lib/ph/io.hoon
  pkg/arvo/lib/ph/util.hoon
  pkg/arvo/lib/pill.hoon
  pkg/arvo/lib/vere.hoon
  pkg/arvo/sur/aquarium.hoon
  pkg/arvo/sur/eth-watcher.hoon
  pkg/arvo/sur/tapp.hoon
  pkg/arvo/sys/vane/ames.hoon
  pkg/arvo/sys/vane/behn.hoon
  pkg/arvo/sys/vane/clay.hoon
  pkg/arvo/sys/vane/dill.hoon
  pkg/arvo/sys/vane/eyre.hoon
  pkg/arvo/sys/vane/gall.hoon
  pkg/arvo/sys/vane/iris.hoon
  pkg/arvo/sys/vane/jael.hoon
  pkg/arvo/sys/zuse.hoon
  pkg/arvo/ted/aqua/eyre-azimuth.hoon
  pkg/arvo/ted/azimuth-tracker.hoon
  pkg/arvo/ted/claz/prep-command.hoon
  pkg/arvo/ted/eth-watcher.hoon
  pkg/arvo/ted/eth/get-timestamps.hoon
  pkg/arvo/ted/eth/read-contract.hoon
  pkg/arvo/tests/sys/vane/clay.hoon
  pkg/arvo/tests/sys/vane/eyre.hoon
  pkg/arvo/tests/sys/vane/gall.hoon
  pkg/arvo/tests/sys/vane/iris.hoon
Labels: breach

#3981 vere: adds versions to all pier artifacts
  pkg/hs/urbit-eventlog-lmdb/lib/Urbit/EventLog/Event.hs
  pkg/hs/urbit-eventlog-lmdb/lib/Urbit/EventLog/LMDB.hs
  pkg/hs/urbit-eventlog-lmdb/package.yaml
  pkg/hs/urbit-king/lib/Urbit/King/EventBrowser.hs
  pkg/hs/urbit-king/lib/Urbit/Vere/LMDB.hs
  pkg/hs/urbit-king/lib/Urbit/Vere/Pier.hs
  pkg/hs/urbit-king/lib/Urbit/Vere/Serf.hs
  pkg/urbit/bench/ur_bench.c
  pkg/urbit/include/noun/events.h
  pkg/urbit/include/noun/manage.h
  pkg/urbit/include/noun/vortex.h
  pkg/urbit/include/vere/vere.h
  pkg/urbit/noun/events.c
  pkg/urbit/noun/manage.c
  pkg/urbit/noun/urth.c
  pkg/urbit/noun/vortex.c
  pkg/urbit/tests/ames_tests.c
  pkg/urbit/tests/hashtable_tests.c
  pkg/urbit/tests/jam_tests.c
  pkg/urbit/tests/jet_tests.c
  pkg/urbit/tests/mug_tests.c
  pkg/urbit/tests/newt_tests.c
  pkg/urbit/tests/noun_tests.c
  pkg/urbit/vere/disk.c
  pkg/urbit/vere/io/ames.c
  pkg/urbit/vere/io/behn.c
  pkg/urbit/vere/io/cttp.c
  pkg/urbit/vere/io/http.c
  pkg/urbit/vere/io/unix.c
  pkg/urbit/vere/lord.c
  pkg/urbit/vere/pier.c
  pkg/urbit/version
  pkg/urbit/worker/serf.c
Labels: breach

#4099 jael: deconstruct wires accurately
  pkg/arvo/sys/vane/jael.hoon
Labels: breach

#4100 vere: webslog atom tanks, and webflogs
  pkg/urbit/vere/io/http.c
  pkg/urbit/vere/lord.c
Labels: vere

#4120 group-on-leave: soften de-path to fix thread and add thread back to observe-hook state
  pkg/arvo/app/observe-hook.hoon
  pkg/arvo/app/spider.hoon
  pkg/arvo/ted/group/on-leave.hoon
Labels: landscape

#4129 jael: account for step in deriving code
  pkg/arvo/sys/vane/jael.hoon
Labels: jael

#4167 drum: update app index early when unlinking
  pkg/arvo/lib/hood/drum.hoon
  pkg/arvo/mar/sole/effect.hoon
  pkg/arvo/sur/sole.hoon
Labels: hood

#4083 vere: report, not crash, on unreasonable -Y and -Z
  pkg/urbit/vere/pier.c
Labels: vere

#4115 vere: commit the specified mountpoint only
  pkg/urbit/vere/io/unix.c
Labels: vere

#4136 hoon: add jet hint for +redo
  pkg/arvo/sys/hoon.hoon
Labels: hoon
