Repository urbit/urbit, pull requests merged in 2021-06, with the labels that each got.

#4942 dill: support next runtime's inputs
  pkg/arvo/sys/lull.hoon
  pkg/arvo/sys/vane/dill.hoon
Labels: dill

#5023 meta: janeway version bump, new glob target
  .github/actions/glob/Dockerfile
  .github/workflows/glob.yml
Labels: ci

#5039 meta: update janeway to v0.15.3.1
  .github/actions/glob/Dockerfile
Labels: ci

#5037 settings: my channel -> my channels
  pkg/interface/src/views/apps/settings/components/lib/LeapSettings.tsx
Labels: landscape
