Repository urbit/urbit, pull requests merged in 2021-01, with the labels that each got.

#4232 Add a GitHub workflow that auto-merges master to release/next-js on push
  .github/workflows/merge.yml
Labels: ci

#4210 file-server: inline docs for actions
  pkg/arvo/sur/file-server.hoon
Labels: docs, userspace

#4233 tally: add generator for measuring group activity
  pkg/arvo/gen/tally.hoon
Labels: generators

#4271 meta: bump janeway version in glob action
  .github/actions/glob/Dockerfile
  .github/actions/glob/entrypoint.sh
Labels: ci

#3416 Applied schizoanalysis: Sanity checking for landscape
  pkg/arvo/app/contact-hook.hoon
  pkg/arvo/app/group-push-hook.hoon
  pkg/arvo/app/group-store.hoon
  pkg/arvo/app/metadata-hook.hoon
  pkg/arvo/app/sane.hoon
  pkg/arvo/lib/pull-hook.hoon
  pkg/arvo/lib/push-hook.hoon
  pkg/arvo/mar/contact-hook-action.hoon
  pkg/arvo/mar/metadata-hook-action.hoon
  pkg/arvo/ted/sane.hoon
Labels: landscape

#4286 Use bot to execute merge workflow
  .github/workflows/merge.yml
Labels: ci

#4239 graph: make the join thread back off
  pkg/arvo/ted/graph/join.hoon
  pkg/interface/src/logic/api/graph.ts
Labels: graph

#4112 AsyncButton: protect against double submit
  package-lock.json
  pkg/interface/package-lock.json
  pkg/interface/package.json
  pkg/interface/src/views/components/AsyncButton.tsx
  pkg/interface/src/views/components/StatelessAsyncAction.tsx
  pkg/interface/src/views/components/StatelessAsyncButton.tsx
Labels: landscape

#4324 Remove use of CACHIX_NAME in build action
  .github/workflows/build.yml
  .github/workflows/release-docker.yml
Labels: ci

#4203 clay: condense +pile-rule
  pkg/arvo/sys/vane/clay.hoon
Labels: clay
