Repository urbit/urbit, pull requests merged in 2022-07, with the labels that each got.

#5855 gall: exclude from traces
  pkg/arvo/sys/vane/gall.hoon
Labels: gall

#5881 u3: add guard page to loom
  pkg/urbit/Makefile
  pkg/urbit/configure
  pkg/urbit/include/c/defs.h
  pkg/urbit/include/noun/allocate.h
  pkg/urbit/include/noun/events.h
  pkg/urbit/include/noun/manage.h
  pkg/urbit/jets/b/reel.c
  pkg/urbit/jets/e/parse.c
  pkg/urbit/noun/allocate.c
  pkg/urbit/noun/events.c
  pkg/urbit/noun/manage.c
  pkg/urbit/noun/nock.c
  pkg/urbit/noun/retrieve.c
  pkg/urbit/noun/serial.c
  pkg/urbit/tests/nock_tests.c
Labels: vere

#5830 aqua: add %aqua-effect mark file
  pkg/arvo/mar/aqua/effect.hoon
Labels: tests

#5901 landscape: new system preferences search
  pkg/grid/src/components/icons/MagnifyingGlassIcon.tsx
  pkg/grid/src/preferences/SearchSystemPrefences.tsx
  pkg/grid/src/preferences/SystemPreferences.tsx
Labels: landscape

#5905 landscape: new appearance prefs
  pkg/grid/package-lock.json
  pkg/grid/package.json
  pkg/grid/src/preferences/ApperancePrefs.tsx
  pkg/grid/src/preferences/SystemPreferences.tsx
Labels: landscape

#5912 Landscape: Add new calm engine prefs
  pkg/grid/src/preferences/AttentionAndPrivacy.tsx
  pkg/grid/src/preferences/SystemPreferences.tsx
  pkg/grid/src/state/settings.ts
Labels: landscape
